package com.numbereater.investmentapp

object Constants {
    /* An array of layouts where the index of each
    layout corresponds to the lesson id */
    val LESSONS = intArrayOf(
        R.layout.lesson_investment_basics,
        R.layout.lesson_setting_financial_goals,
        R.layout.lesson_investment_securities,
        R.layout.lesson_risk_return,
        R.layout.lesson_portfolio_construction,
        R.layout.lesson_investment_strategies,
        R.layout.lesson_tax_considerations
    )
    const val LESSON_COMPLETE_INTENT_TAG = "lesson-complete"
    const val LESSON_ID_INTENT_TAG = "lesson-id"
    const val QUIZ_JSON_INTENT_TAG = "quiz-json"
    
    val QUIZZES = arrayOf(
        LessonQuiz(
            arrayOf(
                QuizQuestion(R.string.investment_basics_q1,
                    arrayOf(
                        R.string.investment_basics_q1_a1,
                        R.string.investment_basics_q1_a2,
                        R.string.investment_basics_q1_a3,
                        R.string.investment_basics_q1_a4,
                        R.string.investment_basics_q1_a5,
                    ),
                    4
                ),
                QuizQuestion(
                    R.string.investment_basics_q2,
                    arrayOf(
                        R.string.investment_basics_q2_a1,
                        R.string.investment_basics_q2_a2,
                        R.string.investment_basics_q2_a3,
                        R.string.investment_basics_q2_a4,
                        R.string.investment_basics_q2_a5,
                    ),
                    2
                ),
                QuizQuestion(
                    R.string.investment_basics_q3,
                    arrayOf(
                        R.string.investment_basics_q3_a1,
                        R.string.investment_basics_q3_a2,
                        R.string.investment_basics_q3_a3,
                        R.string.investment_basics_q3_a4,
                        R.string.investment_basics_q3_a5,
                    ),
                    2
                ),
                QuizQuestion(
                    R.string.investment_basics_q4,
                    arrayOf(
                        R.string.investment_basics_q4_a1,
                        R.string.investment_basics_q4_a2,
                        R.string.investment_basics_q4_a3,
                        R.string.investment_basics_q4_a4,
                        R.string.investment_basics_q4_a5,
                    ),
                    1
                ),
                QuizQuestion(
                    R.string.investment_basics_q5,
                    arrayOf(
                        R.string.investment_basics_q5_a1,
                        R.string.investment_basics_q5_a2,
                        R.string.investment_basics_q5_a3,
                        R.string.investment_basics_q5_a4,
                        R.string.investment_basics_q5_a5,
                    ),
                    1
                )
            ),
            0
        ),
        LessonQuiz(
            arrayOf(
                QuizQuestion(R.string.financial_goals_q1,
                    arrayOf(
                        R.string.financial_goals_q1_a1,
                        R.string.financial_goals_q1_a2,
                        R.string.financial_goals_q1_a3,
                        R.string.financial_goals_q1_a4,
                        R.string.financial_goals_q1_a5,
                    ),
                    2
                ),
                QuizQuestion(
                    R.string.financial_goals_q2,
                    arrayOf(
                        R.string.financial_goals_q2_a1,
                        R.string.financial_goals_q2_a2,
                        R.string.financial_goals_q2_a3,
                        R.string.financial_goals_q2_a4,
                        R.string.financial_goals_q2_a5,
                    ),
                    0
                ),
                QuizQuestion(
                    R.string.financial_goals_q3,
                    arrayOf(
                        R.string.financial_goals_q3_a1,
                        R.string.financial_goals_q3_a2,
                        R.string.financial_goals_q3_a3,
                        R.string.financial_goals_q3_a4,
                        R.string.financial_goals_q3_a5,
                    ),
                    1
                ),
                QuizQuestion(
                    R.string.financial_goals_q4,
                    arrayOf(
                        R.string.financial_goals_q4_a1,
                        R.string.financial_goals_q4_a2,
                        R.string.financial_goals_q4_a3,
                        R.string.financial_goals_q4_a4,
                        R.string.financial_goals_q4_a5,
                    ),
                    1
                ),
                QuizQuestion(
                    R.string.financial_goals_q5,
                    arrayOf(
                        R.string.financial_goals_q5_a1,
                        R.string.financial_goals_q5_a2,
                        R.string.financial_goals_q5_a3,
                        R.string.financial_goals_q5_a4,
                        R.string.financial_goals_q5_a5,
                    ),
                    2
                )
            ),
            1
        ),
        LessonQuiz(
            arrayOf(
                QuizQuestion(R.string.investment_securities_q1,
                    arrayOf(
                        R.string.investment_securities_q1_a1,
                        R.string.investment_securities_q1_a2,
                        R.string.investment_securities_q1_a3,
                        R.string.investment_securities_q1_a4,
                        R.string.investment_securities_q1_a5,
                    ),
                    4
                ),
                QuizQuestion(
                    R.string.investment_securities_q2,
                    arrayOf(
                        R.string.investment_securities_q2_a1,
                        R.string.investment_securities_q2_a2,
                        R.string.investment_securities_q2_a3,
                        R.string.investment_securities_q2_a4,
                        R.string.investment_securities_q2_a5,
                    ),
                    0
                ),
                QuizQuestion(
                    R.string.investment_securities_q3,
                    arrayOf(
                        R.string.investment_securities_q3_a1,
                        R.string.investment_securities_q3_a2,
                        R.string.investment_securities_q3_a3,
                        R.string.investment_securities_q3_a4,
                        R.string.investment_securities_q3_a5,
                    ),
                    3
                ),
                QuizQuestion(
                    R.string.investment_securities_q4,
                    arrayOf(
                        R.string.investment_securities_q4_a1,
                        R.string.investment_securities_q4_a2,
                        R.string.investment_securities_q4_a3,
                        R.string.investment_securities_q4_a4,
                        R.string.investment_securities_q4_a5,
                    ),
                    0
                ),
                QuizQuestion(
                    R.string.investment_securities_q5,
                    arrayOf(
                        R.string.investment_securities_q5_a1,
                        R.string.investment_securities_q5_a2,
                        R.string.investment_securities_q5_a3,
                        R.string.investment_securities_q5_a4,
                        R.string.investment_securities_q5_a5,
                    ),
                    4
                ),
                QuizQuestion(
                    R.string.investment_securities_q6,
                    arrayOf(
                        R.string.investment_securities_q6_a1,
                        R.string.investment_securities_q6_a2,
                        R.string.investment_securities_q6_a3,
                        R.string.investment_securities_q6_a4,
                        R.string.investment_securities_q6_a5,
                    ),
                    2
                ),
                QuizQuestion(
                    R.string.investment_securities_q7,
                    arrayOf(
                        R.string.investment_securities_q7_a1,
                        R.string.investment_securities_q7_a2,
                        R.string.investment_securities_q7_a3,
                        R.string.investment_securities_q7_a4,
                        R.string.investment_securities_q7_a5,
                    ),
                    0
                ),
                QuizQuestion(
                    R.string.investment_securities_q8,
                    arrayOf(
                        R.string.investment_securities_q8_a1,
                        R.string.investment_securities_q8_a2,
                        R.string.investment_securities_q8_a3,
                        R.string.investment_securities_q8_a4,
                        R.string.investment_securities_q8_a5,
                    ),
                    2
                ),
                QuizQuestion(
                    R.string.investment_securities_q9,
                    arrayOf(
                        R.string.investment_securities_q9_a1,
                        R.string.investment_securities_q9_a2,
                        R.string.investment_securities_q9_a3,
                        R.string.investment_securities_q9_a4,
                        R.string.investment_securities_q9_a5,
                    ),
                    4
                ),
                QuizQuestion(
                    R.string.investment_securities_q10,
                    arrayOf(
                        R.string.investment_securities_q10_a1,
                        R.string.investment_securities_q10_a2,
                        R.string.investment_securities_q10_a3,
                        R.string.investment_securities_q10_a4,
                        R.string.investment_securities_q10_a5,
                    ),
                    0
                ),
            ),
            2
        ),
        LessonQuiz(
            arrayOf(
                QuizQuestion(R.string.risk_return_q1,
                    arrayOf(
                        R.string.risk_return_q1_a1,
                        R.string.risk_return_q1_a2,
                        R.string.risk_return_q1_a3,
                        R.string.risk_return_q1_a4,
                        R.string.risk_return_q1_a5,
                    ),
                    0
                ),
                QuizQuestion(
                    R.string.risk_return_q2,
                    arrayOf(
                        R.string.risk_return_q2_a1,
                        R.string.risk_return_q2_a2,
                        R.string.risk_return_q2_a3,
                        R.string.risk_return_q2_a4,
                        R.string.risk_return_q2_a5,
                    ),
                    3
                ),
                QuizQuestion(
                    R.string.risk_return_q3,
                    arrayOf(
                        R.string.risk_return_q3_a1,
                        R.string.risk_return_q3_a2,
                        R.string.risk_return_q3_a3,
                        R.string.risk_return_q3_a4,
                        R.string.risk_return_q3_a5,
                    ),
                    0
                ),
                QuizQuestion(
                    R.string.risk_return_q4,
                    arrayOf(
                        R.string.risk_return_q4_a1,
                        R.string.risk_return_q4_a2,
                        R.string.risk_return_q4_a3,
                        R.string.risk_return_q4_a4,
                        R.string.risk_return_q4_a5,
                    ),
                    2
                ),
                QuizQuestion(
                    R.string.risk_return_q5,
                    arrayOf(
                        R.string.risk_return_q5_a1,
                        R.string.risk_return_q5_a2,
                        R.string.risk_return_q5_a3,
                        R.string.risk_return_q5_a4,
                        R.string.risk_return_q5_a5,
                    ),
                    2
                )
            ),
            3
        ),
        LessonQuiz(
            arrayOf(
                QuizQuestion(R.string.portfolio_construction_q1,
                    arrayOf(
                        R.string.portfolio_construction_q1_a1,
                        R.string.portfolio_construction_q1_a2,
                        R.string.portfolio_construction_q1_a3,
                        R.string.portfolio_construction_q1_a4,
                        R.string.portfolio_construction_q1_a5,
                    ),
                    2
                ),
                QuizQuestion(
                    R.string.portfolio_construction_q2,
                    arrayOf(
                        R.string.portfolio_construction_q2_a1,
                        R.string.portfolio_construction_q2_a2,
                        R.string.portfolio_construction_q2_a3,
                        R.string.portfolio_construction_q2_a4,
                        R.string.portfolio_construction_q2_a5,
                    ),
                    0
                ),
                QuizQuestion(
                    R.string.portfolio_construction_q3,
                    arrayOf(
                        R.string.portfolio_construction_q3_a1,
                        R.string.portfolio_construction_q3_a2,
                        R.string.portfolio_construction_q3_a3,
                        R.string.portfolio_construction_q3_a4,
                        R.string.portfolio_construction_q3_a5,
                    ),
                    3
                ),
                QuizQuestion(
                    R.string.portfolio_construction_q4,
                    arrayOf(
                        R.string.portfolio_construction_q4_a1,
                        R.string.portfolio_construction_q4_a2,
                        R.string.portfolio_construction_q4_a3,
                        R.string.portfolio_construction_q4_a4,
                        R.string.portfolio_construction_q4_a5,
                    ),
                    3
                ),
                QuizQuestion(
                    R.string.portfolio_construction_q5,
                    arrayOf(
                        R.string.portfolio_construction_q5_a1,
                        R.string.portfolio_construction_q5_a2,
                        R.string.portfolio_construction_q5_a3,
                        R.string.portfolio_construction_q5_a4,
                        R.string.portfolio_construction_q5_a5,
                    ),
                    4
                )
            ),
            4
        ),
        LessonQuiz(
            arrayOf(
                QuizQuestion(R.string.investment_strategies_q1,
                    arrayOf(
                        R.string.investment_strategies_q1_a1,
                        R.string.investment_strategies_q1_a2,
                        R.string.investment_strategies_q1_a3,
                        R.string.investment_strategies_q1_a4,
                        R.string.investment_strategies_q1_a5,
                    ),
                    0
                ),
                QuizQuestion(
                    R.string.investment_strategies_q2,
                    arrayOf(
                        R.string.investment_strategies_q2_a1,
                        R.string.investment_strategies_q2_a2,
                        R.string.investment_strategies_q2_a3,
                        R.string.investment_strategies_q2_a4,
                        R.string.investment_strategies_q2_a5,
                    ),
                    3
                ),
                QuizQuestion(
                    R.string.investment_strategies_q3,
                    arrayOf(
                        R.string.investment_strategies_q3_a1,
                        R.string.investment_strategies_q3_a2,
                        R.string.investment_strategies_q3_a3,
                        R.string.investment_strategies_q3_a4,
                        R.string.investment_strategies_q3_a5,
                    ),
                    0
                ),
                QuizQuestion(
                    R.string.investment_strategies_q4,
                    arrayOf(
                        R.string.investment_strategies_q4_a1,
                        R.string.investment_strategies_q4_a2,
                        R.string.investment_strategies_q4_a3,
                        R.string.investment_strategies_q4_a4,
                        R.string.investment_strategies_q4_a5,
                    ),
                    1
                ),
                QuizQuestion(
                    R.string.investment_strategies_q5,
                    arrayOf(
                        R.string.investment_strategies_q5_a1,
                        R.string.investment_strategies_q5_a2,
                        R.string.investment_strategies_q5_a3,
                        R.string.investment_strategies_q5_a4,
                        R.string.investment_strategies_q5_a5,
                    ),
                    2
                )
            ),
            5
        ),
        LessonQuiz(
            arrayOf(
                QuizQuestion(R.string.tax_considerations_q1,
                    arrayOf(
                        R.string.tax_considerations_q1_a1,
                        R.string.tax_considerations_q1_a2,
                        R.string.tax_considerations_q1_a3,
                        R.string.tax_considerations_q1_a4,
                        R.string.tax_considerations_q1_a5,
                    ),
                    1
                ),
                QuizQuestion(
                    R.string.tax_considerations_q2,
                    arrayOf(
                        R.string.tax_considerations_q2_a1,
                        R.string.tax_considerations_q2_a2,
                        R.string.tax_considerations_q2_a3,
                        R.string.tax_considerations_q2_a4,
                        R.string.tax_considerations_q2_a5,
                    ),
                    2
                ),
                QuizQuestion(
                    R.string.tax_considerations_q3,
                    arrayOf(
                        R.string.tax_considerations_q3_a1,
                        R.string.tax_considerations_q3_a2,
                        R.string.tax_considerations_q3_a3,
                        R.string.tax_considerations_q3_a4,
                        R.string.tax_considerations_q3_a5,
                    ),
                    3
                ),
                QuizQuestion(
                    R.string.tax_considerations_q4,
                    arrayOf(
                        R.string.tax_considerations_q4_a1,
                        R.string.tax_considerations_q4_a2,
                        R.string.tax_considerations_q4_a3,
                        R.string.tax_considerations_q4_a4,
                        R.string.tax_considerations_q4_a5,
                    ),
                    3
                ),
                QuizQuestion(
                    R.string.tax_considerations_q5,
                    arrayOf(
                        R.string.tax_considerations_q5_a1,
                        R.string.tax_considerations_q5_a2,
                        R.string.tax_considerations_q5_a3,
                        R.string.tax_considerations_q5_a4,
                        R.string.tax_considerations_q5_a5,
                    ),
                    4
                )
            ),
            6
        )
    )
}